<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PesananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pesanan')->insert([
            [
                'id_pesanan' => 1,
                'id_transaction' => 1,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI0537735158',
                'harga_pengiriman' => 13253.08,
                'keterangan' => 'Aperiam eius voluptas veniam repudiandae at.',
                'slug' => 'pesanan-1',
                'created_at' => '2025-02-24 06:48:58',
                'updated_at' => '2025-02-24 06:48:58'
            ],
            [
                'id_pesanan' => 2,
                'id_transaction' => 2,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI1020539502',
                'harga_pengiriman' => 29437.76,
                'keterangan' => 'Amet qui minima quia labore.',
                'slug' => 'pesanan-2',
                'created_at' => '2025-03-24 08:58:10',
                'updated_at' => '2025-03-24 08:58:10'
            ],
            [
                'id_pesanan' => 3,
                'id_transaction' => 3,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI2499856984',
                'harga_pengiriman' => 29287.26,
                'keterangan' => 'Magni inventore recusandae beatae omnis soluta mollitia.',
                'slug' => 'pesanan-3',
                'created_at' => '2025-05-21 14:26:52',
                'updated_at' => '2025-05-21 14:26:52'
            ],
            [
                'id_pesanan' => 4,
                'id_transaction' => 4,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI5280988516',
                'harga_pengiriman' => 18471.57,
                'keterangan' => 'Sit velit in totam amet enim.',
                'slug' => 'pesanan-4',
                'created_at' => '2025-03-25 12:09:36',
                'updated_at' => '2025-03-25 12:09:36'
            ],
            [
                'id_pesanan' => 5,
                'id_transaction' => 5,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI5022961201',
                'harga_pengiriman' => 26011.85,
                'keterangan' => 'Dolor in exercitationem fuga quam quod necessitatibus.',
                'slug' => 'pesanan-5',
                'created_at' => '2025-05-02 08:14:05',
                'updated_at' => '2025-05-02 08:14:05'
            ],
            [
                'id_pesanan' => 6,
                'id_transaction' => 6,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI0369003432',
                'harga_pengiriman' => 29379.93,
                'keterangan' => 'Enim blanditiis libero inventore consectetur.',
                'slug' => 'pesanan-6',
                'created_at' => '2025-02-02 23:51:25',
                'updated_at' => '2025-02-02 23:51:25'
            ],
            [
                'id_pesanan' => 7,
                'id_transaction' => 7,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI9751613696',
                'harga_pengiriman' => 23504.25,
                'keterangan' => 'Aspernatur sit quia dolore quod asperiores odio.',
                'slug' => 'pesanan-7',
                'created_at' => '2025-07-26 20:01:38',
                'updated_at' => '2025-07-26 20:01:38'
            ],
            [
                'id_pesanan' => 8,
                'id_transaction' => 8,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI5527177449',
                'harga_pengiriman' => 16323.54,
                'keterangan' => 'Explicabo asperiores iure alias.',
                'slug' => 'pesanan-8',
                'created_at' => '2025-07-26 01:35:43',
                'updated_at' => '2025-07-26 01:35:43'
            ],
            [
                'id_pesanan' => 9,
                'id_transaction' => 9,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI7788925546',
                'harga_pengiriman' => 17390.54,
                'keterangan' => 'Quo perspiciatis amet occaecati ex ex.',
                'slug' => 'pesanan-9',
                'created_at' => '2025-05-24 04:53:00',
                'updated_at' => '2025-05-24 04:53:00'
            ],
            [
                'id_pesanan' => 10,
                'id_transaction' => 10,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI5054235733',
                'harga_pengiriman' => 10070.91,
                'keterangan' => 'Culpa eos ratione magni.',
                'slug' => 'pesanan-10',
                'created_at' => '2025-05-31 03:02:22',
                'updated_at' => '2025-05-31 03:02:22'
            ],
            [
                'id_pesanan' => 11,
                'id_transaction' => 11,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI4738347359',
                'harga_pengiriman' => 13991.46,
                'keterangan' => 'Iure eligendi fugit minima vitae repellendus.',
                'slug' => 'pesanan-11',
                'created_at' => '2025-07-29 15:01:41',
                'updated_at' => '2025-07-29 15:01:41'
            ],
            [
                'id_pesanan' => 12,
                'id_transaction' => 12,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI6853615305',
                'harga_pengiriman' => 24570.9,
                'keterangan' => 'Saepe officiis recusandae consequuntur.',
                'slug' => 'pesanan-12',
                'created_at' => '2025-02-23 17:58:04',
                'updated_at' => '2025-02-23 17:58:04'
            ],
            [
                'id_pesanan' => 13,
                'id_transaction' => 13,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI9711798089',
                'harga_pengiriman' => 10887.73,
                'keterangan' => 'Quaerat eos a explicabo necessitatibus.',
                'slug' => 'pesanan-13',
                'created_at' => '2025-04-22 09:54:35',
                'updated_at' => '2025-04-22 09:54:35'
            ],
            [
                'id_pesanan' => 14,
                'id_transaction' => 14,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI0585277221',
                'harga_pengiriman' => 11867.74,
                'keterangan' => 'Alias dicta ratione suscipit et est id.',
                'slug' => 'pesanan-14',
                'created_at' => '2025-03-14 17:53:31',
                'updated_at' => '2025-03-14 17:53:31'
            ],
            [
                'id_pesanan' => 15,
                'id_transaction' => 15,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI6169284511',
                'harga_pengiriman' => 22225.48,
                'keterangan' => 'Optio esse nobis incidunt porro expedita.',
                'slug' => 'pesanan-15',
                'created_at' => '2025-07-30 21:24:46',
                'updated_at' => '2025-07-30 21:24:46'
            ],
            [
                'id_pesanan' => 16,
                'id_transaction' => 16,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI6909275571',
                'harga_pengiriman' => 25568.41,
                'keterangan' => 'Consequuntur facilis et eius vero ad delectus.',
                'slug' => 'pesanan-16',
                'created_at' => '2025-01-17 10:46:43',
                'updated_at' => '2025-01-17 10:46:43'
            ],
            [
                'id_pesanan' => 17,
                'id_transaction' => 17,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI4422583132',
                'harga_pengiriman' => 11678.95,
                'keterangan' => 'Ratione ad mollitia fuga rem.',
                'slug' => 'pesanan-17',
                'created_at' => '2025-07-21 01:44:08',
                'updated_at' => '2025-07-21 01:44:08'
            ],
            [
                'id_pesanan' => 18,
                'id_transaction' => 18,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI6801824225',
                'harga_pengiriman' => 19093.99,
                'keterangan' => 'Exercitationem velit tempora sapiente dolorum.',
                'slug' => 'pesanan-18',
                'created_at' => '2025-02-20 09:33:19',
                'updated_at' => '2025-02-20 09:33:19'
            ],
            [
                'id_pesanan' => 19,
                'id_transaction' => 19,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI3647102767',
                'harga_pengiriman' => 25624.66,
                'keterangan' => 'Dignissimos non est quaerat quasi similique voluptate.',
                'slug' => 'pesanan-19',
                'created_at' => '2025-04-17 14:04:08',
                'updated_at' => '2025-04-17 14:04:08'
            ],
            [
                'id_pesanan' => 20,
                'id_transaction' => 20,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI2787747016',
                'harga_pengiriman' => 14770.9,
                'keterangan' => 'Itaque dolores nesciunt aliquid eligendi nisi sapiente.',
                'slug' => 'pesanan-20',
                'created_at' => '2025-02-20 18:49:43',
                'updated_at' => '2025-02-20 18:49:43'
            ],
            [
                'id_pesanan' => 21,
                'id_transaction' => 21,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI9912165585',
                'harga_pengiriman' => 12038.03,
                'keterangan' => 'Dicta magni magnam aliquid.',
                'slug' => 'pesanan-21',
                'created_at' => '2025-07-02 18:11:14',
                'updated_at' => '2025-07-02 18:11:14'
            ],
            [
                'id_pesanan' => 22,
                'id_transaction' => 22,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI5169409749',
                'harga_pengiriman' => 26991.51,
                'keterangan' => 'Dolorem amet laboriosam minima quam quo fugit.',
                'slug' => 'pesanan-22',
                'created_at' => '2025-02-23 05:16:17',
                'updated_at' => '2025-02-23 05:16:17'
            ],
            [
                'id_pesanan' => 23,
                'id_transaction' => 23,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI7865278585',
                'harga_pengiriman' => 21103.52,
                'keterangan' => 'Nostrum deleniti doloribus nam dolore.',
                'slug' => 'pesanan-23',
                'created_at' => '2025-04-05 01:26:08',
                'updated_at' => '2025-04-05 01:26:08'
            ],
            [
                'id_pesanan' => 24,
                'id_transaction' => 24,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI7473384842',
                'harga_pengiriman' => 13830.82,
                'keterangan' => 'Nulla nesciunt doloribus pariatur.',
                'slug' => 'pesanan-24',
                'created_at' => '2025-04-26 13:58:07',
                'updated_at' => '2025-04-26 13:58:07'
            ],
            [
                'id_pesanan' => 25,
                'id_transaction' => 25,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI8026206724',
                'harga_pengiriman' => 10910.31,
                'keterangan' => 'Ab necessitatibus autem.',
                'slug' => 'pesanan-25',
                'created_at' => '2025-07-26 05:39:55',
                'updated_at' => '2025-07-26 05:39:55'
            ],
            [
                'id_pesanan' => 26,
                'id_transaction' => 26,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI6851612275',
                'harga_pengiriman' => 15292.92,
                'keterangan' => 'Ab fugit ipsum eaque eveniet.',
                'slug' => 'pesanan-26',
                'created_at' => '2025-05-11 02:49:07',
                'updated_at' => '2025-05-11 02:49:07'
            ],
            [
                'id_pesanan' => 27,
                'id_transaction' => 27,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI7279568783',
                'harga_pengiriman' => 23787.42,
                'keterangan' => 'Perspiciatis nisi ratione minima minus.',
                'slug' => 'pesanan-27',
                'created_at' => '2025-01-05 10:35:19',
                'updated_at' => '2025-01-05 10:35:19'
            ],
            [
                'id_pesanan' => 28,
                'id_transaction' => 28,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI7908740640',
                'harga_pengiriman' => 28321.46,
                'keterangan' => 'Neque aliquid exercitationem aperiam voluptatibus.',
                'slug' => 'pesanan-28',
                'created_at' => '2025-05-21 12:04:45',
                'updated_at' => '2025-05-21 12:04:45'
            ],
            [
                'id_pesanan' => 29,
                'id_transaction' => 29,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI3004786863',
                'harga_pengiriman' => 22508.17,
                'keterangan' => 'Itaque culpa deleniti soluta quisquam.',
                'slug' => 'pesanan-29',
                'created_at' => '2025-01-27 19:18:18',
                'updated_at' => '2025-01-27 19:18:18'
            ],
            [
                'id_pesanan' => 30,
                'id_transaction' => 30,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI2843959953',
                'harga_pengiriman' => 27280.54,
                'keterangan' => 'Soluta voluptates maxime impedit eius.',
                'slug' => 'pesanan-30',
                'created_at' => '2025-01-13 12:17:13',
                'updated_at' => '2025-01-13 12:17:13'
            ],
            [
                'id_pesanan' => 31,
                'id_transaction' => 31,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI6882634351',
                'harga_pengiriman' => 11496.56,
                'keterangan' => 'Sed at quam deleniti eaque perferendis nobis.',
                'slug' => 'pesanan-31',
                'created_at' => '2025-03-10 00:21:34',
                'updated_at' => '2025-03-10 00:21:34'
            ],
            [
                'id_pesanan' => 32,
                'id_transaction' => 32,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI7854458771',
                'harga_pengiriman' => 18873.57,
                'keterangan' => 'Quis eum dicta est aliquid sint qui.',
                'slug' => 'pesanan-32',
                'created_at' => '2025-01-29 06:23:56',
                'updated_at' => '2025-01-29 06:23:56'
            ],
            [
                'id_pesanan' => 33,
                'id_transaction' => 33,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI8728080100',
                'harga_pengiriman' => 13399.67,
                'keterangan' => 'Consequuntur occaecati architecto corrupti dolor iste.',
                'slug' => 'pesanan-33',
                'created_at' => '2025-01-07 07:10:49',
                'updated_at' => '2025-01-07 07:10:49'
            ],
            [
                'id_pesanan' => 34,
                'id_transaction' => 34,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI3398454615',
                'harga_pengiriman' => 20617.05,
                'keterangan' => 'Itaque doloribus possimus error repudiandae aspernatur.',
                'slug' => 'pesanan-34',
                'created_at' => '2025-01-24 11:26:09',
                'updated_at' => '2025-01-24 11:26:09'
            ],
            [
                'id_pesanan' => 35,
                'id_transaction' => 35,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI1489025039',
                'harga_pengiriman' => 17371.71,
                'keterangan' => 'Quibusdam quae id aspernatur.',
                'slug' => 'pesanan-35',
                'created_at' => '2025-01-13 07:19:15',
                'updated_at' => '2025-01-13 07:19:15'
            ],
            [
                'id_pesanan' => 36,
                'id_transaction' => 36,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI5866296194',
                'harga_pengiriman' => 21746.81,
                'keterangan' => 'Quae aspernatur culpa quae odio.',
                'slug' => 'pesanan-36',
                'created_at' => '2025-03-05 02:08:45',
                'updated_at' => '2025-03-05 02:08:45'
            ],
            [
                'id_pesanan' => 37,
                'id_transaction' => 37,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI5604661839',
                'harga_pengiriman' => 28781.06,
                'keterangan' => 'Cumque fugit consequuntur error laudantium aperiam ipsa.',
                'slug' => 'pesanan-37',
                'created_at' => '2025-06-01 07:32:24',
                'updated_at' => '2025-06-01 07:32:24'
            ],
            [
                'id_pesanan' => 38,
                'id_transaction' => 38,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI4593752654',
                'harga_pengiriman' => 23255.37,
                'keterangan' => 'Voluptas quos eveniet eligendi ratione facilis ut.',
                'slug' => 'pesanan-38',
                'created_at' => '2025-06-13 12:57:29',
                'updated_at' => '2025-06-13 12:57:29'
            ],
            [
                'id_pesanan' => 39,
                'id_transaction' => 39,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI7979688680',
                'harga_pengiriman' => 26261.06,
                'keterangan' => 'Praesentium repellat nisi totam autem dolorum.',
                'slug' => 'pesanan-39',
                'created_at' => '2025-03-19 14:16:17',
                'updated_at' => '2025-03-19 14:16:17'
            ],
            [
                'id_pesanan' => 40,
                'id_transaction' => 40,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI0714611254',
                'harga_pengiriman' => 25970.28,
                'keterangan' => 'Iste dignissimos laboriosam labore ipsa possimus.',
                'slug' => 'pesanan-40',
                'created_at' => '2025-05-18 20:55:19',
                'updated_at' => '2025-05-18 20:55:19'
            ],
            [
                'id_pesanan' => 41,
                'id_transaction' => 41,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI3796603341',
                'harga_pengiriman' => 19040.11,
                'keterangan' => 'Aut sit deleniti eveniet itaque ea similique.',
                'slug' => 'pesanan-41',
                'created_at' => '2025-05-04 20:27:06',
                'updated_at' => '2025-05-04 20:27:06'
            ],
            [
                'id_pesanan' => 42,
                'id_transaction' => 42,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI5286692966',
                'harga_pengiriman' => 11313.64,
                'keterangan' => 'Laborum modi ullam ut.',
                'slug' => 'pesanan-42',
                'created_at' => '2025-07-24 22:39:37',
                'updated_at' => '2025-07-24 22:39:37'
            ],
            [
                'id_pesanan' => 43,
                'id_transaction' => 43,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI0340438427',
                'harga_pengiriman' => 11931.29,
                'keterangan' => 'Quia quisquam mollitia beatae beatae quod reprehenderit.',
                'slug' => 'pesanan-43',
                'created_at' => '2025-03-09 06:39:55',
                'updated_at' => '2025-03-09 06:39:55'
            ],
            [
                'id_pesanan' => 44,
                'id_transaction' => 44,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI9233095849',
                'harga_pengiriman' => 23400.27,
                'keterangan' => 'Cumque voluptatem eos nemo veritatis maiores tempore.',
                'slug' => 'pesanan-44',
                'created_at' => '2025-05-23 11:23:58',
                'updated_at' => '2025-05-23 11:23:58'
            ],
            [
                'id_pesanan' => 45,
                'id_transaction' => 45,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI4577590175',
                'harga_pengiriman' => 10579.06,
                'keterangan' => 'Recusandae id voluptas repudiandae.',
                'slug' => 'pesanan-45',
                'created_at' => '2025-02-06 23:33:46',
                'updated_at' => '2025-02-06 23:33:46'
            ],
            [
                'id_pesanan' => 46,
                'id_transaction' => 46,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI4241541520',
                'harga_pengiriman' => 11391.71,
                'keterangan' => 'Numquam quas quidem inventore at atque.',
                'slug' => 'pesanan-46',
                'created_at' => '2025-07-12 03:04:39',
                'updated_at' => '2025-07-12 03:04:39'
            ],
            [
                'id_pesanan' => 47,
                'id_transaction' => 47,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI2218909275',
                'harga_pengiriman' => 15442.06,
                'keterangan' => 'Occaecati corrupti illum placeat similique.',
                'slug' => 'pesanan-47',
                'created_at' => '2025-03-24 21:13:46',
                'updated_at' => '2025-03-24 21:13:46'
            ],
            [
                'id_pesanan' => 48,
                'id_transaction' => 48,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI3640376137',
                'harga_pengiriman' => 20538.68,
                'keterangan' => 'Architecto suscipit accusamus facere et harum saepe in.',
                'slug' => 'pesanan-48',
                'created_at' => '2025-02-03 15:59:27',
                'updated_at' => '2025-02-03 15:59:27'
            ],
            [
                'id_pesanan' => 49,
                'id_transaction' => 49,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI1418328569',
                'harga_pengiriman' => 25346.99,
                'keterangan' => 'Est ipsa veritatis dolores.',
                'slug' => 'pesanan-49',
                'created_at' => '2025-03-09 02:20:09',
                'updated_at' => '2025-03-09 02:20:09'
            ],
            [
                'id_pesanan' => 50,
                'id_transaction' => 50,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI4814917785',
                'harga_pengiriman' => 10374.83,
                'keterangan' => 'Libero necessitatibus facilis ducimus.',
                'slug' => 'pesanan-50',
                'created_at' => '2025-04-05 22:42:59',
                'updated_at' => '2025-04-05 22:42:59'
            ],
            [
                'id_pesanan' => 51,
                'id_transaction' => 51,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI4195180238',
                'harga_pengiriman' => 26640.52,
                'keterangan' => 'Veritatis architecto iure.',
                'slug' => 'pesanan-51',
                'created_at' => '2025-02-09 23:08:35',
                'updated_at' => '2025-02-09 23:08:35'
            ],
            [
                'id_pesanan' => 52,
                'id_transaction' => 52,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI8505064138',
                'harga_pengiriman' => 20612.1,
                'keterangan' => 'In vero voluptate consequuntur eius.',
                'slug' => 'pesanan-52',
                'created_at' => '2025-04-20 15:17:26',
                'updated_at' => '2025-04-20 15:17:26'
            ],
            [
                'id_pesanan' => 53,
                'id_transaction' => 53,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI5743132912',
                'harga_pengiriman' => 13542.92,
                'keterangan' => 'Cum iure illo modi.',
                'slug' => 'pesanan-53',
                'created_at' => '2025-01-18 01:10:48',
                'updated_at' => '2025-01-18 01:10:48'
            ],
            [
                'id_pesanan' => 54,
                'id_transaction' => 54,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI8317121003',
                'harga_pengiriman' => 19234.85,
                'keterangan' => 'Dicta id placeat vel.',
                'slug' => 'pesanan-54',
                'created_at' => '2025-03-22 15:18:35',
                'updated_at' => '2025-03-22 15:18:35'
            ],
            [
                'id_pesanan' => 55,
                'id_transaction' => 55,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI5324472099',
                'harga_pengiriman' => 19254.23,
                'keterangan' => 'Doloribus eos illum mollitia aperiam eius consequatur dicta.',
                'slug' => 'pesanan-55',
                'created_at' => '2025-02-02 15:18:15',
                'updated_at' => '2025-02-02 15:18:15'
            ],
            [
                'id_pesanan' => 56,
                'id_transaction' => 56,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI0785932133',
                'harga_pengiriman' => 18175.39,
                'keterangan' => 'Modi recusandae qui quisquam veniam.',
                'slug' => 'pesanan-56',
                'created_at' => '2025-07-24 04:56:32',
                'updated_at' => '2025-07-24 04:56:32'
            ],
            [
                'id_pesanan' => 57,
                'id_transaction' => 57,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI9308705932',
                'harga_pengiriman' => 16204.63,
                'keterangan' => 'Quaerat ullam sapiente eum accusantium nesciunt.',
                'slug' => 'pesanan-57',
                'created_at' => '2025-05-31 20:21:37',
                'updated_at' => '2025-05-31 20:21:37'
            ],
            [
                'id_pesanan' => 58,
                'id_transaction' => 58,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI2209690295',
                'harga_pengiriman' => 23238.58,
                'keterangan' => 'Dolore natus vel consequuntur quia dolores voluptatem cumque.',
                'slug' => 'pesanan-58',
                'created_at' => '2025-02-25 00:17:54',
                'updated_at' => '2025-02-25 00:17:54'
            ],
            [
                'id_pesanan' => 59,
                'id_transaction' => 59,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI8617932710',
                'harga_pengiriman' => 24423.66,
                'keterangan' => 'Accusantium ea autem exercitationem suscipit.',
                'slug' => 'pesanan-59',
                'created_at' => '2025-02-04 10:59:10',
                'updated_at' => '2025-02-04 10:59:10'
            ],
            [
                'id_pesanan' => 60,
                'id_transaction' => 60,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI4310698720',
                'harga_pengiriman' => 28106.12,
                'keterangan' => 'A assumenda reprehenderit numquam laboriosam atque.',
                'slug' => 'pesanan-60',
                'created_at' => '2025-03-04 11:44:18',
                'updated_at' => '2025-03-04 11:44:18'
            ],
            [
                'id_pesanan' => 61,
                'id_transaction' => 61,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI7743490211',
                'harga_pengiriman' => 14811.28,
                'keterangan' => 'Repellat impedit quidem dolorem aperiam harum.',
                'slug' => 'pesanan-61',
                'created_at' => '2025-03-22 08:56:29',
                'updated_at' => '2025-03-22 08:56:29'
            ],
            [
                'id_pesanan' => 62,
                'id_transaction' => 62,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI6163294511',
                'harga_pengiriman' => 24946.33,
                'keterangan' => 'Nam mollitia sequi maxime totam accusamus.',
                'slug' => 'pesanan-62',
                'created_at' => '2025-07-22 22:49:11',
                'updated_at' => '2025-07-22 22:49:11'
            ],
            [
                'id_pesanan' => 63,
                'id_transaction' => 63,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI9960653074',
                'harga_pengiriman' => 26270.18,
                'keterangan' => 'Accusantium repellendus esse eligendi laudantium possimus.',
                'slug' => 'pesanan-63',
                'created_at' => '2025-07-22 22:37:51',
                'updated_at' => '2025-07-22 22:37:51'
            ],
            [
                'id_pesanan' => 64,
                'id_transaction' => 64,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI8902330307',
                'harga_pengiriman' => 27715.81,
                'keterangan' => 'Ullam provident earum.',
                'slug' => 'pesanan-64',
                'created_at' => '2025-02-08 03:27:08',
                'updated_at' => '2025-02-08 03:27:08'
            ],
            [
                'id_pesanan' => 65,
                'id_transaction' => 65,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI2933334680',
                'harga_pengiriman' => 12489.5,
                'keterangan' => 'Labore consequatur cupiditate.',
                'slug' => 'pesanan-65',
                'created_at' => '2025-06-30 06:49:46',
                'updated_at' => '2025-06-30 06:49:46'
            ],
            [
                'id_pesanan' => 66,
                'id_transaction' => 66,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI4417154544',
                'harga_pengiriman' => 20261.72,
                'keterangan' => 'Deleniti maxime dolores animi similique.',
                'slug' => 'pesanan-66',
                'created_at' => '2025-01-04 06:53:15',
                'updated_at' => '2025-01-04 06:53:15'
            ],
            [
                'id_pesanan' => 67,
                'id_transaction' => 67,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI2417248251',
                'harga_pengiriman' => 28976.47,
                'keterangan' => 'Explicabo quia esse ratione ex.',
                'slug' => 'pesanan-67',
                'created_at' => '2025-06-06 22:28:13',
                'updated_at' => '2025-06-06 22:28:13'
            ],
            [
                'id_pesanan' => 68,
                'id_transaction' => 68,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI2521752500',
                'harga_pengiriman' => 22991.21,
                'keterangan' => 'Earum quis cumque quisquam laudantium quis at.',
                'slug' => 'pesanan-68',
                'created_at' => '2025-04-12 04:35:17',
                'updated_at' => '2025-04-12 04:35:17'
            ],
            [
                'id_pesanan' => 69,
                'id_transaction' => 69,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI6894210447',
                'harga_pengiriman' => 20513.91,
                'keterangan' => 'Nisi excepturi suscipit voluptatum exercitationem temporibus facere.',
                'slug' => 'pesanan-69',
                'created_at' => '2025-06-18 10:29:00',
                'updated_at' => '2025-06-18 10:29:00'
            ],
            [
                'id_pesanan' => 70,
                'id_transaction' => 70,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI0100167618',
                'harga_pengiriman' => 25355.63,
                'keterangan' => 'Labore corrupti possimus occaecati error.',
                'slug' => 'pesanan-70',
                'created_at' => '2025-03-15 04:15:28',
                'updated_at' => '2025-03-15 04:15:28'
            ],
            [
                'id_pesanan' => 71,
                'id_transaction' => 71,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI7530011972',
                'harga_pengiriman' => 26850.6,
                'keterangan' => 'Quod asperiores quam temporibus.',
                'slug' => 'pesanan-71',
                'created_at' => '2025-02-09 05:12:01',
                'updated_at' => '2025-02-09 05:12:01'
            ],
            [
                'id_pesanan' => 72,
                'id_transaction' => 72,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI5794155216',
                'harga_pengiriman' => 23022.6,
                'keterangan' => 'Vitae earum harum sed reiciendis officiis.',
                'slug' => 'pesanan-72',
                'created_at' => '2025-03-31 18:34:12',
                'updated_at' => '2025-03-31 18:34:12'
            ],
            [
                'id_pesanan' => 73,
                'id_transaction' => 73,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI1450899358',
                'harga_pengiriman' => 20001.56,
                'keterangan' => 'Porro nulla inventore quas laboriosam optio odit.',
                'slug' => 'pesanan-73',
                'created_at' => '2025-03-06 18:29:25',
                'updated_at' => '2025-03-06 18:29:25'
            ],
            [
                'id_pesanan' => 74,
                'id_transaction' => 74,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI7797177517',
                'harga_pengiriman' => 17859.09,
                'keterangan' => 'Aut impedit nam.',
                'slug' => 'pesanan-74',
                'created_at' => '2025-02-27 17:33:35',
                'updated_at' => '2025-02-27 17:33:35'
            ],
            [
                'id_pesanan' => 75,
                'id_transaction' => 75,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI5488510272',
                'harga_pengiriman' => 10378.75,
                'keterangan' => 'Autem nostrum deleniti ut hic itaque.',
                'slug' => 'pesanan-75',
                'created_at' => '2025-01-01 01:34:54',
                'updated_at' => '2025-01-01 01:34:54'
            ],
            [
                'id_pesanan' => 76,
                'id_transaction' => 76,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI9958669346',
                'harga_pengiriman' => 20703.05,
                'keterangan' => 'Voluptas iste consequatur impedit praesentium quibusdam.',
                'slug' => 'pesanan-76',
                'created_at' => '2025-03-16 00:19:22',
                'updated_at' => '2025-03-16 00:19:22'
            ],
            [
                'id_pesanan' => 77,
                'id_transaction' => 77,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI6081062003',
                'harga_pengiriman' => 21355.62,
                'keterangan' => 'Quibusdam cum enim dolorum saepe.',
                'slug' => 'pesanan-77',
                'created_at' => '2025-04-27 02:04:20',
                'updated_at' => '2025-04-27 02:04:20'
            ],
            [
                'id_pesanan' => 78,
                'id_transaction' => 78,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI5989334721',
                'harga_pengiriman' => 25075.13,
                'keterangan' => 'Vitae quasi blanditiis aliquam.',
                'slug' => 'pesanan-78',
                'created_at' => '2025-04-25 14:54:34',
                'updated_at' => '2025-04-25 14:54:34'
            ],
            [
                'id_pesanan' => 79,
                'id_transaction' => 79,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI1826886153',
                'harga_pengiriman' => 11242.49,
                'keterangan' => 'Optio ex eos veniam nulla.',
                'slug' => 'pesanan-79',
                'created_at' => '2025-04-19 09:30:52',
                'updated_at' => '2025-04-19 09:30:52'
            ],
            [
                'id_pesanan' => 80,
                'id_transaction' => 80,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI8877043581',
                'harga_pengiriman' => 10634.7,
                'keterangan' => 'Cumque vero modi ab.',
                'slug' => 'pesanan-80',
                'created_at' => '2025-07-04 09:59:23',
                'updated_at' => '2025-07-04 09:59:23'
            ],
            [
                'id_pesanan' => 81,
                'id_transaction' => 81,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI4667665061',
                'harga_pengiriman' => 20638.67,
                'keterangan' => 'Ab quam aperiam quia aliquid sed facere.',
                'slug' => 'pesanan-81',
                'created_at' => '2025-01-26 10:14:29',
                'updated_at' => '2025-01-26 10:14:29'
            ],
            [
                'id_pesanan' => 82,
                'id_transaction' => 82,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI2100996881',
                'harga_pengiriman' => 22519.86,
                'keterangan' => 'Distinctio qui quas distinctio temporibus.',
                'slug' => 'pesanan-82',
                'created_at' => '2025-07-15 06:46:48',
                'updated_at' => '2025-07-15 06:46:48'
            ],
            [
                'id_pesanan' => 83,
                'id_transaction' => 83,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI4913577594',
                'harga_pengiriman' => 27472.41,
                'keterangan' => 'Corrupti necessitatibus repellat vero cumque et quos quae.',
                'slug' => 'pesanan-83',
                'created_at' => '2025-07-19 01:20:14',
                'updated_at' => '2025-07-19 01:20:14'
            ],
            [
                'id_pesanan' => 84,
                'id_transaction' => 84,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI9969308488',
                'harga_pengiriman' => 10324.4,
                'keterangan' => 'Omnis corrupti hic tempora nihil similique consequatur.',
                'slug' => 'pesanan-84',
                'created_at' => '2025-06-19 08:58:15',
                'updated_at' => '2025-06-19 08:58:15'
            ],
            [
                'id_pesanan' => 85,
                'id_transaction' => 85,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI3038567700',
                'harga_pengiriman' => 20478.89,
                'keterangan' => 'Aut voluptas odio earum quia neque.',
                'slug' => 'pesanan-85',
                'created_at' => '2025-07-14 14:48:23',
                'updated_at' => '2025-07-14 14:48:23'
            ],
            [
                'id_pesanan' => 86,
                'id_transaction' => 86,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI2259136517',
                'harga_pengiriman' => 24143.39,
                'keterangan' => 'Laboriosam nihil officia illum doloribus consectetur nihil.',
                'slug' => 'pesanan-86',
                'created_at' => '2025-03-09 12:23:51',
                'updated_at' => '2025-03-09 12:23:51'
            ],
            [
                'id_pesanan' => 87,
                'id_transaction' => 87,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI9298425799',
                'harga_pengiriman' => 23185.69,
                'keterangan' => 'Dolorem harum autem dicta.',
                'slug' => 'pesanan-87',
                'created_at' => '2025-02-22 07:43:08',
                'updated_at' => '2025-02-22 07:43:08'
            ],
            [
                'id_pesanan' => 88,
                'id_transaction' => 88,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI6599162473',
                'harga_pengiriman' => 20714.76,
                'keterangan' => 'Eligendi soluta illum deleniti.',
                'slug' => 'pesanan-88',
                'created_at' => '2025-07-15 20:58:17',
                'updated_at' => '2025-07-15 20:58:17'
            ],
            [
                'id_pesanan' => 89,
                'id_transaction' => 89,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI8872588744',
                'harga_pengiriman' => 26304.29,
                'keterangan' => 'Exercitationem provident quasi sequi omnis quibusdam ipsum.',
                'slug' => 'pesanan-89',
                'created_at' => '2025-01-03 18:18:28',
                'updated_at' => '2025-01-03 18:18:28'
            ],
            [
                'id_pesanan' => 90,
                'id_transaction' => 90,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI6984902770',
                'harga_pengiriman' => 21317.13,
                'keterangan' => 'Sed ut maxime deserunt quos.',
                'slug' => 'pesanan-90',
                'created_at' => '2025-03-04 20:02:23',
                'updated_at' => '2025-03-04 20:02:23'
            ],
            [
                'id_pesanan' => 91,
                'id_transaction' => 91,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI9554393769',
                'harga_pengiriman' => 23540.7,
                'keterangan' => 'Ea illum autem.',
                'slug' => 'pesanan-91',
                'created_at' => '2025-07-18 06:39:03',
                'updated_at' => '2025-07-18 06:39:03',
            ],
            [
                'id_pesanan' => 92,
                'id_transaction' => 92,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI6588043416',
                'harga_pengiriman' => 20015.86,
                'keterangan' => 'Asperiores ut labore explicabo tempora eaque.',
                'slug' => 'pesanan-92',
                'created_at' => '2025-01-29 02:41:10',
                'updated_at' => '2025-01-29 02:41:10',
            ],
            [
                'id_pesanan' => 93,
                'id_transaction' => 93,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI4728463920',
                'harga_pengiriman' => 11713.88,
                'keterangan' => 'Reiciendis laboriosam molestiae magnam hic placeat cupiditate.',
                'slug' => 'pesanan-93',
                'created_at' => '2025-03-15 20:29:22',
                'updated_at' => '2025-03-15 20:29:22',
            ],
            [
                'id_pesanan' => 94,
                'id_transaction' => 94,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI2763655647',
                'harga_pengiriman' => 24233.54,
                'keterangan' => 'Necessitatibus voluptatem placeat repellendus.',
                'slug' => 'pesanan-94',
                'created_at' => '2025-02-16 17:54:45',
                'updated_at' => '2025-02-16 17:54:45',
            ],
            [
                'id_pesanan' => 95,
                'id_transaction' => 95,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI2034717545',
                'harga_pengiriman' => 21938.49,
                'keterangan' => 'Nam ut ducimus accusantium commodi sint.',
                'slug' => 'pesanan-95',
                'created_at' => '2025-04-15 20:06:28',
                'updated_at' => '2025-04-15 20:06:28',
            ],
            [
                'id_pesanan' => 96,
                'id_transaction' => 96,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI1125355449',
                'harga_pengiriman' => 29060.09,
                'keterangan' => 'Earum ipsam sint facilis nesciunt vitae.',
                'slug' => 'pesanan-96',
                'created_at' => '2025-03-19 06:25:26',
                'updated_at' => '2025-03-19 06:25:26',
            ],
            [
                'id_pesanan' => 97,
                'id_transaction' => 97,
                'status' => 'selesai',
                'jasa_pengiriman' => 'J&T',
                'no_resi' => 'RESI6433472282',
                'harga_pengiriman' => 20213.52,
                'keterangan' => 'Alias explicabo totam.',
                'slug' => 'pesanan-97',
                'created_at' => '2025-06-10 18:39:27',
                'updated_at' => '2025-06-10 18:39:27',
            ],
            [
                'id_pesanan' => 98,   
                'id_transaction' => 98,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI0825478077',
                'harga_pengiriman' => 16237.81,
                'keterangan' => 'Ab inventore eos doloremque ab.',
                'slug' => 'pesanan-98',
                'created_at' => '2025-07-04 22:05:01',
                'updated_at' => '2025-07-04 22:05:01',
            ],
            [
                'id_pesanan' => 99,
                'id_transaction' => 99,
                'status' => 'selesai',
                'jasa_pengiriman' => 'JNE',
                'no_resi' => 'RESI1797497350',
                'harga_pengiriman' => 26983.6,
                'keterangan' => 'Amet modi delectus aut.',
                'slug' => 'pesanan-99',
                'created_at' => '2025-05-26 02:36:48',
                'updated_at' => '2025-05-26 02:36:48',
            ],
            [
                'id_pesanan' => 100,
                'id_transaction' => 100,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI1872346013',
                'harga_pengiriman' => 14637.11,
                'keterangan' => 'Quo ipsam qui alias itaque quo.',
                'slug' => 'pesanan-100',
                'created_at' => '2025-04-15 13:04:49',
                'updated_at' => '2025-04-15 13:04:49',
            ],
            [
                'id_pesanan' => 101,
                'id_transaction' => 101,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI2491630097',
                'harga_pengiriman' => 12279.1,
                'keterangan' => 'Culpa quo dolorum libero placeat excepturi voluptas quis.',
                'slug' => 'pesanan-101',
                'created_at' => '2025-07-22 09:22:07',
                'updated_at' => '2025-07-22 09:22:07',
            ],
            [
                'id_pesanan' => 102,
                'id_transaction' => 102,
                'status' => 'selesai',
                'jasa_pengiriman' => 'SiCepat',
                'no_resi' => 'RESI9285574982',
                'harga_pengiriman' => 12338.98,
                'keterangan' => 'Minus ipsum reprehenderit molestiae.',
                'slug' => 'pesanan-102',
                'created_at' => '2025-01-24 07:43:42',
                'updated_at' => '2025-01-24 07:43:42',
            ],
            [
                'id_pesanan' => 103,
                'id_transaction' => 103,
                'status' => 'selesai',
                'jasa_pengiriman' => 'AnterAja',
                'no_resi' => 'RESI1181022031',
                'harga_pengiriman' => 12730.69,
                'keterangan' => 'Deleniti adipisci odit harum laudantium numquam nihil.',
                'slug' => 'pesanan-103',
                'created_at' => '2025-06-26 08:19:22',
                'updated_at' => '2025-06-26 08:19:22',
            ],
        ]);
    }
}
