<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();
        
        // Data untuk tabel produk_master
        $produkMaster = [
            [
                'id_master_produk' => 1,
                'id_ktg_produk' => 1,
                'nama_produk' => 'Tas Selempang',
                'deskripsi' => '<p>Tas Selempang</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"tas"}]',
                'meta_desc' => '<p>Tas Selempang</p>',
                'gambar' => 'produk/thumbnails/2luXTGvwypOZaRLLGe1F0WqXosHBxukfu76YxGf5.jpg',
                'slug' => '5be4c479084570457c44301bb5e16d97',
                'created_at' => '2025-07-02 15:55:13',
                'updated_at' => '2025-07-02 15:55:13',
            ],
            [
                'id_master_produk' => 2,
                'id_ktg_produk' => 1,
                'nama_produk' => 'Tas Handphone',
                'deskripsi' => '<p>Tas Handphone</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"tas"},{"value":"handphone"}]',
                'meta_desc' => '<p>Tas Handphone</p>',
                'gambar' => 'produk/thumbnails/6TjHzcCjSqZseWNaBlrcY071dsJVUXEBNgbhYoUP.jpg',
                'slug' => '970d0bb46ff6984246048ed3384bad4f',
                'created_at' => '2025-07-02 15:56:57',
                'updated_at' => '2025-07-02 15:56:57',
            ],
            [
                'id_master_produk' => 3,
                'id_ktg_produk' => 1,
                'nama_produk' => 'Ransel-Basic',
                'deskripsi' => '<p>Ransel-Basic</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"ransel"}]',
                'meta_desc' => '<p>Ransel-Basic</p>',
                'gambar' => 'produk/thumbnails/cUEFEhH0YmnRZWwd48PySpjMAbOMWUON6tfl5pP5.jpg',
                'slug' => '01ff860fc5cd89801ae8250b2749a3e6',
                'created_at' => '2025-07-02 16:03:14',
                'updated_at' => '2025-07-02 16:03:14',
            ],
            [
                'id_master_produk' => 4,
                'id_ktg_produk' => 1,
                'nama_produk' => 'Ransel-Uair',
                'deskripsi' => '<p>Ransel-Uair</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"ransel"}]',
                'meta_desc' => '<p>Ransel-Uair</p>',
                'gambar' => 'produk/thumbnails/yQMZxTmsXZUVwDdEBTAuTFOUT3WDVG0E9T8aPbPX.jpg',
                'slug' => 'c122427474853e91241db6ebd7d6a2ac',
                'created_at' => '2025-07-02 16:07:09',
                'updated_at' => '2025-07-02 16:07:09',
            ],
            [
                'id_master_produk' => 5,
                'id_ktg_produk' => 1,
                'nama_produk' => 'Tas Kecil Siro',
                'deskripsi' => '<p>Tas Kecil Siro</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"siro"}]',
                'meta_desc' => '<p>Tas Kecil Siro</p>',
                'gambar' => 'produk/thumbnails/Ov0FncerVZqTCLAboVqw3pfuiNtRCxckwfxaALCq.jpg',
                'slug' => 'dcf66bcecc0701c514866affcac305dd',
                'created_at' => '2025-07-02 16:11:10',
                'updated_at' => '2025-07-02 16:11:10',
            ],
            [
                'id_master_produk' => 6,
                'id_ktg_produk' => 1,
                'nama_produk' => 'Tas Sakura',
                'deskripsi' => '<p>Tas Sakura</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"sakura"}]',
                'meta_desc' => '<p>Tas Sakura</p>',
                'gambar' => 'produk/thumbnails/R3ba3XzYrgyTAr0IazLhHWVimhhpEEAUm6ywO32D.jpg',
                'slug' => 'ac93035bf03e5585d716b7a9d1651611',
                'created_at' => '2025-07-02 16:12:46',
                'updated_at' => '2025-07-02 16:12:46',
            ],
            [
                'id_master_produk' => 7,
                'id_ktg_produk' => 2,
                'nama_produk' => 'Topi Anak',
                'deskripsi' => '<p>Topi Anak</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"topi"}]',
                'meta_desc' => '<p>Topi Anak</p>',
                'gambar' => 'produk/thumbnails/XjYfvbhmfcT39NPtbcLnaiB7aeTCYFAuYJmLQpWj.jpg',
                'slug' => '34b0c5953d279c773a6ed739ef4a53be',
                'created_at' => '2025-07-02 16:14:08',
                'updated_at' => '2025-07-02 16:14:08',
            ],
            [
                'id_master_produk' => 8,
                'id_ktg_produk' => 2,
                'nama_produk' => 'Buckethead Rajut-Motif',
                'deskripsi' => '<p>Buckethead Rajut-Motif</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"topi"}]',
                'meta_desc' => '<p>Buckethead Rajut-Motif</p>',
                'gambar' => 'produk/thumbnails/IHLiih9moFOT5qZ5bD6yAgmkFGkqPVK2FxStuH0s.jpg',
                'slug' => 'c7daf832e4aa4b51f7744f4f04b42373',
                'created_at' => '2025-07-02 16:22:22',
                'updated_at' => '2025-07-02 16:22:22',
            ],
            [
                'id_master_produk' => 9,
                'id_ktg_produk' => 2,
                'nama_produk' => 'Topi Kiru',
                'deskripsi' => '<p>Topi Kiru</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"topi"}]',
                'meta_desc' => '<p>Topi Kiru</p>',
                'gambar' => 'produk/thumbnails/4HhJLTRTFu09XFvEXAhgCxoGWNFIg2sjYxfLFviO.jpg',
                'slug' => 'fe0fb995e769ef82a9a02867ad56b1f4',
                'created_at' => '2025-07-02 16:23:34',
                'updated_at' => '2025-07-02 16:23:34',
            ],
            [
                'id_master_produk' => 10,
                'id_ktg_produk' => 3,
                'nama_produk' => 'Syal Polos',
                'deskripsi' => '<p>Syal Polos</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"syal"}]',
                'meta_desc' => '<p>Syal polos</p>',
                'gambar' => 'produk/thumbnails/7FMlITyTKCOc5ZV8BjwKy2ojuiW4D25dSV25R8nT.jpg',
                'slug' => '99b6e84e1ae80cd6f0524a3beed19cf8',
                'created_at' => '2025-07-02 16:24:31',
                'updated_at' => '2025-07-02 16:29:24',
            ],
            [
                'id_master_produk' => 11,
                'id_ktg_produk' => 3,
                'nama_produk' => 'Syal Motif Chees',
                'deskripsi' => '<p>Syal Motif Chees</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"discounted"},{"value":"syal"}]',
                'meta_desc' => '<p>Syal Motif Chees</p>',
                'gambar' => 'produk/thumbnails/054EGE4cxXfrySUoaxCFRUBILDP4MC9psh6x2crr.jpg',
                'slug' => 'd27e4c1690068cb7f9f1c2e4d301ae5e',
                'created_at' => '2025-07-02 16:25:53',
                'updated_at' => '2025-07-02 16:25:53',
            ],
            [
                'id_master_produk' => 12,
                'id_ktg_produk' => 3,
                'nama_produk' => 'Syal Garis Rainbow',
                'deskripsi' => '<p>Syal Garis Rainbow</p>',
                'status' => 'published',
                'use_variant' => 'no',
                'meta_keywords' => '[{"value":"new"},{"value":"trending"},{"value":"sale"},{"value":"syal"}]',
                'meta_desc' => '<p>Syal Garis Rainbow</p>',
                'gambar' => 'produk/thumbnails/iWAZy3NZNbpwic7kdsDiSmLodAX0cCL4bkzSBAlN.jpg',
                'slug' => '3a19d3a20a10a55c6f549678caf38f2c',
                'created_at' => '2025-07-02 16:28:38',
                'updated_at' => '2025-07-02 16:28:38',
            ],
        ];

        // Data untuk tabel detail_produk_master
        $detailProdukMaster = [
            [
                'id_detail_produk' => 1,
                'id_master_produk' => 1,
                'sku' => 'SKU-TSSLPG',
                'harga' => 150000,
                'stok' => '50',
                'slug' => '5be4c479084570457c44301bb5e16d97',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 2,
                'id_master_produk' => 2,
                'sku' => 'SKU-TSHP',
                'harga' => 100000,
                'stok' => '60',
                'slug' => '970d0bb46ff6984246048ed3384bad4f',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 3,
                'id_master_produk' => 3,
                'sku' => 'SKU-TSRSB',
                'harga' => 200000,
                'stok' => '40',
                'slug' => '01ff860fc5cd89801ae8250b2749a3e6',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 4,
                'id_master_produk' => 4,
                'sku' => 'SKU-TSRSU',
                'harga' => 230000,
                'stok' => '60',
                'slug' => 'c122427474853e91241db6ebd7d6a2ac',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 5,
                'id_master_produk' => 5,
                'sku' => 'SKU-TSSR',
                'harga' => 150000,
                'stok' => '56',
                'slug' => 'dcf66bcecc0701c514866affcac305dd',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 6,
                'id_master_produk' => 6,
                'sku' => 'SKU-TSSKR',
                'harga' => 120000,
                'stok' => '40',
                'slug' => 'ac93035bf03e5585d716b7a9d1651611',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 7,
                'id_master_produk' => 7,
                'sku' => 'SKU-TPKCL',
                'harga' => 80000,
                'stok' => '50',
                'slug' => '34b0c5953d279c773a6ed739ef4a53be',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 8,
                'id_master_produk' => 8,
                'sku' => 'SKU-TPBCHD',
                'harga' => 70000,
                'stok' => '50',
                'slug' => 'c7daf832e4aa4b51f7744f4f04b42373',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 9,
                'id_master_produk' => 9,
                'sku' => 'SKU-TPKR',
                'harga' => 70000,
                'stok' => '40',
                'slug' => 'fe0fb995e769ef82a9a02867ad56b1f4',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 10,
                'id_master_produk' => 10,
                'sku' => 'SKU-SYLPLS',
                'harga' => 75000,
                'stok' => '50',
                'slug' => '99b6e84e1ae80cd6f0524a3beed19cf8',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 11,
                'id_master_produk' => 11,
                'sku' => 'SKU-SYMCS',
                'harga' => 80000,
                'stok' => '40',
                'slug' => 'd27e4c1690068cb7f9f1c2e4d301ae5e',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id_detail_produk' => 12,
                'id_master_produk' => 12,
                'sku' => 'SKU-SYGRBW',
                'harga' => 75000,
                'stok' => '50',
                'slug' => '3a19d3a20a10a55c6f549678caf38f2c',
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        // Insert data ke tabel produk_master
        DB::table('produk_master')->insert($produkMaster);
        
        // Insert data ke tabel detail_produk_master
        DB::table('detail_produk_master')->insert($detailProdukMaster);

        $this->command->info('Data produk master dan detail produk master berhasil ditambahkan!');
    }
}