networks:
  nurfa-network:

volumes:
  nurfa-data:
  caddy_data:
  caddy_config:

services:
    nurfa-app:
      container_name: nurfa-app
      build: 
        context: .
        dockerfile: Dockerfile.prod
      ports:
        - "8000:8000"
      volumes:
        - /app/vendor
      env_file:
        - .env.prod
      depends_on:
        nurfa-mysql:
          condition: service_healthy
      networks:
        - nurfa-network


    nurfa-mysql:
      container_name: nurfa-mysql
      image: mysql:latest
      environment:
        MYSQL_DATABASE: db-nurfa
        MYSQL_USER: nurfa
        MYSQL_PASSWORD: dbnurfa
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3307:3306"
      volumes:
        - nurfa-data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        retries: 5
        start_period: 20s
      networks:
        - nurfa-network

    nurfa-caddy:
      container_name: nurfa-caddy
      image: caddy:alpine
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - nurfa-app
      networks:
        - nurfa-network
