networks:
  nurfa-network:

volumes:
  nurfa-data:

services:
    nurfa-app:
      container_name: nurfa-app
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "7000:8000"
      volumes:
        - .:/app
        - /app/vendor
      env_file:
        - .env
      depends_on:
        nurfa-mysql:
          condition: service_healthy

    nurfa-mysql:
      container_name: nurfa-mysql
      image: mysql:latest
      environment:
        MYSQL_DATABASE: db-nurfa
        MYSQL_USER: nurfa
        MYSQL_PASSWORD: dbnurfa
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3307:3306"
      volumes:
        - nurfa-data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        retries: 5
        start_period: 20s

    nurfa-phpmyadmin:
      container_name: nurfa-phpmyadmin
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: nurfa-mysql
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "7080:80"
      depends_on:
        - nurfa-mysql