networks:
  nurfa-network:
  web:

volumes:
  nurfa-data:
  traefik-certificates:

services:
  nurfa-app:
    container_name: nurfa-app
    build: 
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /app/vendor
    env_file:
      - .env.prod
    depends_on:
      nurfa-mysql:
        condition: service_healthy
    networks:
      - nurfa-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nurfacraft.rule=Host(`nurfa-craft.store`)"
      - "traefik.http.routers.nurfacraft.entrypoints=websecure"
      - "traefik.http.routers.nurfacraft.tls.certresolver=letsencrypt"
      - "traefik.http.services.nurfacraft.loadbalancer.server.port=80"

  nurfa-mysql:
    image: mysql:8
    container_name: nurfa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nurfa_db
    volumes:
      - nurfa-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nurfa-network

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=you@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/letsencrypt/acme.json
    networks:
      - web
